"""added login column

Revision ID: 87108d885b64
Revises: 
Create Date: 2025-07-01 09:43:30.694034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87108d885b64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login')

    # ### end Alembic commands ###
